version: '3.1'

services:
  client:
    container_name: greenmoons-client
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - greenmoons-networks

  # nginx:
  #   container_name: greenmoons-nginx
  #   build:
  #     context: ./nginx
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - '80:80'
  #   networks:
  #     - greenmoons-networks

networks:
  greenmoons-networks:
    driver: bridge
